doctrine:
    dbal:
        dbname: '%env(DB_NAME)%'
        host: '%env(DB_HOST)%'
        port: '%env(DB_PORT)%'
        user: '%env(DB_USER)%'
        password: '%env(DB_PASSWORD)%'
        driver: '%env(DB_DRIVER)%'
        server_version: '%env(DB_VERSION)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
                type: annotation
