version: '3'
services:
  database:
    image: mysql:5.7
    environment:
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
